[package]
name = "j-k-ratio-plus-L"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["serde_derive"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
