name: publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: run the magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: build container
        run: |
          nix build .#container
      - uses: docker/setup-buildx-action@v2
      - run: docker load --input ./result
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ghcr.io/jgero/j-k-ratio-plus-uppercase-l
